export const SKILLS = [
  { id: "01", icon: FaHtml5, skill: "HTML", progress: 90, type: "frontend" },
  { id: "02", icon: FaCss3Alt, skill: "CSS", progress: 85, type: "frontend" },
  {
    id: "03",
    icon: FaReact,
    skill: "React JS",
    progress: 75,
    type: "frontend",
  },
  {
    id: "04",
    icon: TbBrandReactNative,
    skill: "React Native",
    progress: 60,
    type: "frontend",
  },
  {
    id: "05",
    icon: TbBrandTailwind,
    skill: "Tailwind CSS",
    progress: 80,
    type: "frontend",
  },
  { id: "06", icon: SiPython, skill: "Python", progress: 70, type: "backend" },
  { id: "07", icon: SiCsharp, skill: "C#", progress: 65, type: "backend" },
  { id: "08", icon: SiMerise, skill: "Merise", progress: 50, type: "skills" },
  { id: "09", icon: SiUml, skill: "UML", progress: 55, type: "skills" },
  {
    id: "10",
    icon: SiVisualstudiocode,
    skill: "VS Code",
    progress: 85,
    type: "tools",
  },
  {
    id: "11",
    icon: SiVisualstudio,
    skill: "Visual Studio",
    progress: 80,
    type: "tools",
  },
  {
    id: "12",
    icon: SiMicrosoftsqlserver,
    skill: "SQL Server",
    progress: 75,
    type: "tools",
  },
  {
    id: "13",
    icon: SiFigma,
    skill: "Figma",
    progress: 55,
    type: "tools",
  },
];
